### ISSUE TITLE
Prepare tutorial showing how to simulate a network

### ISSUE THREAD

**Issue by xyzsam** [harvard-acc/smaug#4]
We need a full tutorial of how to implement a new network and simulate it, going all the way from Python to C++ to gem5-Aladdin.

**Comment by xyzsam** [comment]
Yuan - can you add a page to the docs about running a model through simulation?

**Comment by yaoyuannnn** [comment]
> Yuan - can you add a page to the docs about running a model through simulation?

Sure Sam. Let me do this in the coming week. I can use the examples already created under `experiments`.

**Comment by yaoyuannnn** [comment]
#92 is created for this.
